title: Browser Fingerprinting
description: Reference sheets for Chrome browser APIs used in browser fingerprinting.
theme: just-the-docs

url: https://prescience-data.github.io/fingerprinting

aux_links:
