title: Browser Fingerprinting
description: Reference sheets for browser APIs used in browser fingerprinting.
theme: just-the-docs

url: https://fingerprinting.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
